apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: sso
    app.kubernetes.io/part-of: tackle
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: ""
