kind: Secret
apiVersion: v1
metadata:
  name: ""
  labels:
    app.kubernetes.io/name: ""
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: ""
    app.kubernetes.io/part-of: tackle
data:
  database-name: ""
  database-password: ""
  database-user: ""
type: Opaque