#apiVersion: v1
#kind: Namespace
#metadata:
#  name: tackle-operator
#---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
#  namespace: my-keycloak-operator
spec:
  targetNamespaces:
    - tackle-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quarkus-operator
#  namespace: tackle-operator
spec:
  channel: alpha
  name: quarkus-operator
  source: quarkus-operator-test-catalog
  sourceNamespace: olm
