name: Operator test-suite execution

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Operator version'
        required: true
        default: '1.0.0'
      repositoryUser:
        description: 'Test scenario tags'
        required: true
        default: 'mrizzi'
      repositoryBranch:
        description: 'Test scenario tags'
        required: true
        default: 'tackle-upstream-1.0.0'

jobs:
  upstream-build:
    runs-on: ubuntu-latest
    steps:
      - run: bash <(curl -sL https://cutt.ly/WhkV76k) all upstream-community-operators/tackle-operator/${{ github.event.inputs.version }} https://github.com/${{ github.event.inputs.repositoryUser }}/community-operators ${{ github.event.inputs.repositoryBranch }}
        shell: 'script -q -e -c "bash {0}"'
        name: Upstream build