name: Windup Web project build

on:
  workflow_dispatch:

jobs:
  windup-web-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-10.15]
      fail-fast: false
    steps:
      - name: Checkout Windup Web project
        uses: actions/checkout@v3
        with:
          repository: 'mrizzi/windup-web'
          ref: 'containerized-build'
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'
      - name: Install Tools for MacOs
        uses: docker-practice/actions-setup-docker@v1
      - name: Run the build
        run: mvn docker:start -N -s settings.xml
